networks:
    codearena-lan:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16

services:
    empty:
        build: .
        command: ["./my-src/empty"]
        networks:
            - codearena-lan
        privileged: true
        ports:
            - "3000-3010:3000"
        stop_grace_period: 1s
